### ISSUE TITLE
This command does not finish:  nh←HttpCommand.Get 'http://www.kela.fi/web/en/statistics-by-topic_statistics-on-child-day-care-subsidies'

### ISSUE THREAD

**Issue by dyavc** [Dyalog/library-conga#11]
Reproduced in DSS 2021-01-18 18.0.39845.0, 64-bit 18.0 Unicode_DV_64.exe  02c20cd8    
conga dll 3.3.1542 

HttpCommand.Version
⍝⍝⍝HttpCommand 3.1.1 2021-02-04

nh←HttpCommand.Get 'http://www.kela.fi/web/en/statistics-by-topic_statistics-on-child-day-care-subsidies'

does not return/terminate

**Comment by bpbecker** [comment]
This particular URL has a circular redirection
 https://www.kela.fi/web/en/statistics-by-topic_statistics-on-child-day-care-subsidies  redirects to
 /en/web/en/statistics-by-topic_statistics-on-child-day-care-subsidies  which redirects to
 /en/web/en/statistics-by-topic_statistics-on-child-day-care-subsidies 

HttpCommand should catch such a case.  I will amend it to do so.

Opening the original URL in FireFox results in "The page isn’t redirecting properly"

**Comment by bpbecker** [comment]
Fixed by https://github.com/Dyalog/library-conga/commit/ddaae7ee224113d9e5d297736cc3f7cfa639c19f
